Created review card for mobile without get data
ValentinaTenus/reviewED_fe pull request #47
Opened 2024-09-27 14:52 UTC by andrii-rykal

2024-09-27 15:36 UTC, ValentinaTenus requested changes

2024-09-27 15:36 UTC, ValentinaTenus commented on src/common/components/star-rating/index.tsx
> +							<span className={styles["rating_stars"]} key={index}>
why did you add this className here?

2024-09-27 15:36 UTC, ValentinaTenus commented on src/pages/moderators-page/components/main-content/components/review-card/index.tsx
> +/* eslint-disable @typescript-eslint/no-magic-numbers */
please, don't disable rules, use const instead of hardcoded numbers

2024-09-27 15:36 UTC, ValentinaTenus commented on src/pages/moderators-page/components/main-content/components/review-card/index.tsx
> +	const [istruncated, setIsTruncated] = useState(false);
replace with isTruncated

2024-09-27 15:36 UTC, ValentinaTenus commented on src/pages/moderators-page/components/main-content/components/review-card/index.tsx
> +import cn from "classnames";
we already use clsx

2024-09-27 15:36 UTC, ValentinaTenus commented on src/pages/moderators-page/components/main-content/components/review-card/index.tsx
> +				<div className={`${style["card__title"]} ${style["title"]}`}>
use clsx

2024-09-27 15:36 UTC, ValentinaTenus commented on src/pages/moderators-page/components/main-content/components/review-card/index.tsx
> +						onClick={() => setIsTruncated(!istruncated)}
create handler for this

2024-09-27 15:36 UTC, ValentinaTenus commented on src/pages/moderators-page/components/main-content/components/review-card/index.tsx
> +							className={clsx(style["button_fixed"])}
you don't need clsx for only one class

2024-09-27 15:36 UTC, ValentinaTenus commented on src/pages/moderators-page/components/main-content/components/review-card/styles.module.scss
> +		// text-overflow: ellipsis;
delete comments

2024-09-29 07:16 UTC, andrii-rykal commented on src/common/components/star-rating/index.tsx
> +							<span className={styles["rating_stars"]} key={index}>
svg - інлайновий елемент. Знаходиться в середині span, який також інлайновий. Коли ми задаємо Flexbox до контейнера в якому знаходяться spans, то це робить span блоковим, але svg в середині span залишається інлайновим і має додатковий простір під собою, що заважає центруванню. Так як я не можу додати клас до цих спанів через пропси, то вирішив додати в компоненті існуючий клас, який робить тільки flex та центрування.

2024-09-29 14:25 UTC, merged