created company reviews stats section
ValentinaTenus/reviewED_fe pull request #56
Opened 2024-09-30 16:24 UTC by illyadmytrenko

2024-10-01 06:10 UTC, illyadmytrenko commented on src/common/constants/reviews-sort-options.ts
> +	},
i couldn't find them too, so I just made them as the example.

2024-10-01 06:10 UTC, illyadmytrenko commented on src/common/types/company/company.type.ts
>  	total_reviews_count: number;
As far as I understand, review_count is count of reviews for only a company, the same goes for avg_rating, but total_reviews_count is count of reviews not only for company but also for courses that this company provide, so it's simply a sum of the sum of reviews of everything related to the company. And the same goes to avg_overall_rating.

2024-10-01 18:39 UTC, ValentinaTenus commented on src/common/types/company/company.type.ts
>  	total_reviews_count: number;
thanks a lot

2024-10-02 16:20 UTC, ValentinaTenus approved these changes

2024-10-02 16:20 UTC, ValentinaTenus commented on src/pages/company-details-page/components/company-details/components/contacts/contacts.tsx
> +							onClick={() => (window.location.href = `mailto:${company.email}`)}
I'd create handler for this

2024-10-02 16:20 UTC, ValentinaTenus commented on src/pages/company-details-page/components/company-details/components/reviews/components/components/review-modal.tsx
> +	) => {
Use useCallback hook

2024-10-02 16:20 UTC, ValentinaTenus commented on src/pages/company-details-page/components/company-details/components/reviews/components/components/review-modal.tsx
> +	const handleCloseReviewModal = () => {
Use useCallback for handlers

2024-10-03 11:07 UTC, ValentinaTenus requested changes

2024-10-03 11:07 UTC, ValentinaTenus commented on src/common/components/modal/styles.module.scss
> +	// border-bottom: 1px solid var(--color-grey-300);
delete comment

2024-10-03 11:07 UTC, ValentinaTenus commented on src/pages/company-details-page/components/company-details/components/reviews/components/components/report-modal.tsx
> +		// eslint-disable-next-line @typescript-eslint/no-unused-vars
why do you need this

2024-10-03 11:07 UTC, ValentinaTenus commented on src/pages/company-details-page/components/company-details/components/reviews/components/components/review-modal.tsx
> +		console.log(response);
delete

2024-10-03 11:07 UTC, ValentinaTenus commented on src/pages/company-details-page/components/company-details/components/reviews/components/components/share-modal.tsx
> +					return `https://twitter.com/intent/tweet?url=${encodedLink}`;
add to env and env.example

2024-10-03 11:41 UTC, merged