added like to review
ValentinaTenus/reviewED_fe pull request #73
Opened 2024-10-03 13:39 UTC by illyadmytrenko

2024-10-03 18:17 UTC, KirillSerg commented on src/common/components/sort-dropdown/index.tsx
> -	name,
it is necessary, do not delete it. PR @ValentinaTenus  or mine will have a fix

2024-10-04 08:54 UTC, ValentinaTenus requested changes

2024-10-04 08:54 UTC, ValentinaTenus commented on src/pages/company-details-page/components/company-details/components/reviews/components/review-card.tsx
> +						/>
why do you use Link here but not Button?

2024-10-04 08:54 UTC, ValentinaTenus commented on src/pages/company-details-page/components/company-details/components/reviews/components/statistics.tsx
> +	);
use data from api

2024-10-06 11:40 UTC, ValentinaTenus approved these changes

2024-10-06 11:40 UTC, ValentinaTenus commented on src/pages/company-details-page/components/company-details/components/reviews/components/components/review-modal.tsx
> +				window.location.href = AppRoute.PRIVACY_POLICY;
you can use useNavigate hook instead

2024-10-07 08:56 UTC, ValentinaTenus approved these changes

2024-10-07 08:56 UTC, merged